disabled_rules:
  - trailing_whitespace
  - identifier_name
  - force_try
  - line_length

opt_in_rules:
  - empty_count

included:
  - Sources
  - Tests
  - WhipTip

excluded:
  - Legacy
  - WHIPTIP-main

reporter: "xcode"
