name: Swift CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Build & Test (SwiftPM)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        swift: ['5.9']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install SwiftLint (macOS only)
        if: startsWith(matrix.os, 'macos')
        run: |
          brew update
          brew install swiftlint
      - name: Lint
        if: startsWith(matrix.os, 'macos')
        run: |
          swiftlint --version
          swiftlint --strict
      - name: Set up Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test -v
